-- 1.
INSERT INTO TB_CLASS_TYPE VALUES(01, '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES(02, '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES(03, '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES(04, '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES(05, '논문지도');
ROLLBACK;
                            
-- 2.
CREATE TABLE TB_학생일반정보 AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
                             FROM TB_STUDENT);
                             
-- 3.
CREATE TABLE TB_국어국문학과 AS
(SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생이름" , 
    CASE
        WHEN SUBSTR(STUDENT_SSN, 1, 2) <= TO_CHAR(SYSDATE, 'YY') THEN
            TO_CHAR(TO_DATE(2000 + TO_NUMBER(SUBSTR(STUDENT_SSN, 1, 2)) || SUBSTR(STUDENT_SSN, 3, 4)), 'YYYY')
        ELSE 
            TO_CHAR(TO_DATE(1900 + TO_NUMBER(SUBSTR(STUDENT_SSN, 1, 2)) || SUBSTR(STUDENT_SSN, 3, 4)), 'YYYY')
        END AS "출생년도", 
    PROFESSOR_NAME AS "교수이름"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '국어국문학과');

-- 4.
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);
ROLLBACK;

-- 5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NAME = '박건우';

-- 6.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

-- 7.
UPDATE TB_GRADE
SET POINT = 3.5
WHERE STUDENT_NO = (SELECT STUDENT_NO
                      FROM TB_STUDENT
                      JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                     WHERE STUDENT_NAME = '김명훈' AND DEPARTMENT_NAME = '의학과')
    AND CLASS_NO = (SELECT CLASS_NO
                      FROM TB_CLASS
                     WHERE CLASS_NAME = '피부생리학');

-- 8.
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');
                