-- 1.
CREATE TABLE TB_CATEGORY (
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2.
CREATE TABLE TB_CLASS_TYPE (
    NO VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3.
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY (NAME);

-- 4.
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5.
ALTER TABLE TB_CATEGORY
        MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE 
        MODIFY NO VARCHAR2(10)
        MODIFY NAME VARCHAR2(20);
        
        
-- 6.
ALTER TABLE TB_CATEGORY 
        RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
        RENAME COLUMN NO TO CLASS_TYPE_NO;
        
ALTER TABLE TB_CLASS_TYPE
        RENAME COLUMN NAME TO CALSS_TYPE_NAME;

-- 7.
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT SYS_C007186 TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007185 TO PK_CLASS_NO;

-- 8.
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('자연공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');
COMMIT;

-- 9.
ALTER TABLE TB_DEPARTMENT ADD 
CONSTRAINT FK_DEPARTMENT_CATEGORY 
FOREIGN KEY(CATEGORY)
REFERENCES TB_CATEGORY(CATEGORY_NAME);


-- 10.
CREATE VIEW VW_학생일반정보
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT);
     
-- 11.
CREATE VIEW VW_지도면담
AS (SELECT STUDENT_NO, STUDENT_NAME, PROFESSOR_NAME
    FROM TB_STUDENT
    JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO));
    
-- 12.
CREATE VIEW VW_학과별학생수
AS (SELECT DEPARTMENT_NAME, COUNT(DEPARTMENT_NAME) AS "STUDENT_COUNT"
      FROM TB_DEPARTMENT
      JOIN TB_STUDENT USING(DEPARTMENT_NO)
     GROUP BY DEPARTMENT_NAME);

-- 13.
UPDATE "VW_학생일반정보"
SET STUDENT_NAME = '최용준'
WHERE STUDENT_NO = 'A213046';

-- 14.
CREATE VIEW VW_뷰이름
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT)
WITH READ ONLY;


-- 15. 포기
SELECT CLASS_NO, CLASS_NAME, COUNT()
FROM (SELECT CLASS_NO, CLASS_NAME, RANK() OVER(ORDER BY COUNT(STUDENT_NAME) DESC) AS "누적수강생수(명)"
        FROM TB_STUDENT
        JOIN TB_GRADE USING (STUDENT_NO)
        JOIN TB_CLASS USING (CLASS_NO)
        WHERE SUBSTR(TERM_NO, 1, 4) >= '2006' 
        GROUP BY CLASS_NO, CLASS_NAME)
WHERE "누적수강생수(명)" <= 3;